### ISSUE TITLE
Consider .app file extension

### ISSUE THREAD

**Issue by FryingPanBrock** [AppImage/AppImageSpec#42]
In addition to the usual .AppImage file extension, consider also simply **.app**, since that is a more user-friendly and marketable extension. The current extension .AppImage is very long, whereas .app (with a lowercase **a**) would be shorter, simpler and more in line with Windows and Mac where their executables use the extensions .exe and .app. Thus users would feel more at home seeing a file ending with such an extension and instantly recognise it as an app/program; they would not think “what image? is this a picture?” and would not need to be explained what an ISO image is.

To reiterate, I am suggesting a backwards-compatible change, not a replacement of the extension .AppImage; the new extension .app would be the new default, while the old extension .AppImage would continue to work to preserve compatibility with existing AppImages. There would be no confusion with Mac software as it cannot run on Linux — except in some cases with WINE, but that is another topic.

I am aware that I can simply rename my .AppImage files to .app; that is not the point. The point is about all AppImage files in general going forward, not just mine.

**Comment by probonopd** [comment]
Thanks for your suggestion, but we won't consider `.app`, as it is already taken by Mac OS X application bundles and `.AppImage` is working well for our purposes.

For your own use, you can even remove the extension altogether.
