### ISSUE TITLE
~/Applications directory?

### ISSUE THREAD

**Issue by Samueru-sama** [AppImage/AppImageSpec#46]
I noticed that the spec has no mentions of the `~/Applications` directory.

While appimages are made to be run from any location, several tools normally look for several common locations to integrate appimages, one of those locations is usually `~/Applications` and iirc it is the default location used by AppImageLauncher and others. 

Something I don't like is that `~/Applications` is in english, for example ES-DE will look for appimages in `~/Applications`.

I think this location has to have its own env variable akin to the XDG user directories, something like `XDG_APPLICATIONS_DIR` which would default to `~/Applications` when not set but the user can change to anything of their liking, including their language.

Appimage daemons also look for appimages in `~/Downloads` do they follow the XDG user directories and also look in `XDG_DOWNLOAD_DIR`?

**Comment by TheAssassin** [comment]
`~/Applications` is a concept primarily used in AppImageLauncher. It is not translated for a purpose, as it is not standard to any distribution or desktop environment. Please create a discussion in AppImageLauncher's repository to discuss the directory.

**Comment by Samueru-sama** [comment]
> `~/Applications` is a concept primarily used in AppImageLauncher. It is not translated for a purpose, as it is not standard to any distribution or desktop environment. Please create a discussion in AppImageLauncher's repository to discuss the directory.

That's the problem though, that on some instances `~/Applications` ends up being hardcoded like in the case of ES-DE and that is what I want to avoid, if it were added as a env variable to the spec then that's all that the appimage integration tools have to look for instead, that way one doesn't need to go to each separate repo asking for the ability to that location to be changed in the application itself, which is more work than the application checking a env variable.

Also isn't that taken from MacOS?

**Comment by TheAssassin** [comment]
Again, the specification does not contain information to this because it has not originated from the core AppImage tooling and spec.

**Comment by probonopd** [comment]
The AppImage file format is intentionally designed so that users can put AppImages anywhere in the filesystem, including CD-ROMs, DVDs, USB drives, network shares, etc. - on the `$PATH` or out of the  `$PATH`.

There is no recommended location. That is up to the individual desktop environments.

People have put them in `/bin`, `$HOME/.local/bin/`, `/opt`, `~/Downloads`, to name just a few examples.
